### ISSUE TITLE
type parsers

### ISSUE THREAD

**Issue by gajus** [gajus/postgres-bridge#2]
The challenge is that `pg` accepts a function that resolves types at runtime, e.g.

```ts
types: {
  getTypeParser: (oid: number) => {
    if (oid !== NUMERIC_OID) {
      throw new Error('Unexpected OID.');
    }

    return (value: string) => {
      return Number.parseFloat(value);
    };
  },
},
```

Meanwhile, `postgres` accepts a statically typed list, e.g.

```ts
types: [
  {
    from: [
      NUMERIC_OID,
    ],
    parse: (value: string) => {
      return Number.parseFloat(value);
    },
  },
],
```

**Comment by gajus** [comment]
This has now been addressed with a little trick:

https://github.com/gajus/postgres-bridge/blob/2463f7fcb4fad147eadbfbbdf6683b838c53c9e2/src/bridge.ts#L120-L145

**Comment by valeneiko** [comment]
This is still an issue.
https://github.com/gajus/postgres-bridge/blob/cdd2a0cd09bb3242bd1f78cc0ca7ade44cb4e2d7/src/bridge.ts#L137-L142
The object is missing required properties. Here is the expected type definition from `postgres`:
[types/index.d.ts#L318-323](https://github.com/porsager/postgres/blob/b49ed8e9f3c41b664b41b7eb0aa27063207e4cdd/types/index.d.ts#L318-L323)
```ts
  interface PostgresType<T = any> {
    to: number;
    from: number[];
    serialize: (value: T) => unknown;
    parse: (raw: any) => T;
  }
```

`to` and `serialize` are missing.

When `postgres` creates serializers, it will contain `undefined` for this type. Which will result in an error, when it attempts to call that serializer.
